apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: server1-deployment
spec:
 selector:
  matchLabels:
   server: A
 replicas: 1
 template:
  metadata:
   labels:
    server: A
  spec:
   containers:
   - name: server1
     image: sugun/server1:v1
     ports:
     - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
 name: server1-service
spec:
 type: NodePort
 ports:
 - port: 80
   targetPort: 8090
   nodePort: 30025
   protocol: TCP
 selector:
  server: A
